<?xml version="1.0" encoding="utf-8"?><Database Name="db48660631ac154a67865da117016c2257" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=48660631-ac15-4a67-865d-a117016c2257.sqlserver.sequelizer.com;Initial Catalog=db48660631ac154a67865da117016c2257;Persist Security Info=True;User ID=jqaneriqhafcnove" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db48660631ac154a67865da117016c2257ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Names" Member="Names">
    <Type Name="Name">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Member="name1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Times" Member="Times">
    <Type Name="Time">
      <Column Name="time" Member="time1" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>