<?xml version="1.0" encoding="utf-8"?><Database Name="db48660631ac154a67865da117016c2257" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=48660631-ac15-4a67-865d-a117016c2257.sqlserver.sequelizer.com;Initial Catalog=db48660631ac154a67865da117016c2257;Persist Security Info=True;User ID=jqaneriqhafcnove" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db48660631ac154a67865da117016c2257ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WordList" Member="WordLists">
    <Type Name="WordList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="WordList_Word" Member="Words" ThisKey="ID" OtherKey="WordListID" Type="Word" />
      <Association Name="WordList_StudiesUser" Member="StudiesUsers" ThisKey="ID" OtherKey="WordListID" Type="StudiesUser" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="User_TrialBlock" Member="TrialBlocks" ThisKey="ID" OtherKey="UserID" Type="TrialBlock" />
      <Association Name="User_StudiesUser" Member="StudiesUsers" ThisKey="ID" OtherKey="UserID" Type="StudiesUser" />
    </Type>
  </Table>
  <Table Name="dbo.WordSublist" Member="WordSublists">
    <Type Name="WordSublist">
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="WordSublist_Word" Member="Words" ThisKey="ID" OtherKey="WordSublistID" Type="Word" />
      <Association Name="WordSublist_StudiesUser" Member="StudiesUsers" ThisKey="ID" OtherKey="WordSublistID" Type="StudiesUser" />
    </Type>
  </Table>
  <Table Name="dbo.Consequence" Member="Consequences">
    <Type Name="Consequence">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Consequence_Word" Member="Words" ThisKey="ID" OtherKey="ConsequenceID" Type="Word" />
      <Association Name="Consequence_Study" Member="Studies" ThisKey="ID" OtherKey="ControlConsequenceID" Type="Study" />
    </Type>
  </Table>
  <Table Name="dbo.Word" Member="Words">
    <Type Name="Word">
      <Column Name="English" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hawaiian" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ConsequenceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordListID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordSublistID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Word_Trial" Member="Trials" ThisKey="ID" OtherKey="WordID" Type="Trial" />
      <Association Name="Word_Trial1" Member="Trials1" ThisKey="ID" OtherKey="OptionIDClicked" Type="Trial" />
      <Association Name="Word_Trial2" Member="Trials2" ThisKey="ID" OtherKey="Option1ID" Type="Trial" />
      <Association Name="Word_Trial3" Member="Trials3" ThisKey="ID" OtherKey="Option2ID" Type="Trial" />
      <Association Name="Word_Trial4" Member="Trials4" ThisKey="ID" OtherKey="Option3ID" Type="Trial" />
      <Association Name="Consequence_Word" Member="Consequence" ThisKey="ConsequenceID" OtherKey="ID" Type="Consequence" IsForeignKey="true" />
      <Association Name="WordList_Word" Member="WordList" ThisKey="WordListID" OtherKey="ID" Type="WordList" IsForeignKey="true" />
      <Association Name="WordSublist_Word" Member="WordSublist" ThisKey="WordSublistID" OtherKey="ID" Type="WordSublist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrialType" Member="TrialTypes">
    <Type Name="TrialType">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="TrialType_TrialBlock" Member="TrialBlocks" ThisKey="ID" OtherKey="TrialTypeID" Type="TrialBlock" />
      <Association Name="TrialType_StudiesUser" Member="StudiesUsers" ThisKey="ID" OtherKey="TrialTypeID" Type="StudiesUser" />
    </Type>
  </Table>
  <Table Name="dbo.Trial" Member="Trials">
    <Type Name="Trial">
      <Column Name="WordID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrialBlockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeFirstIDpresented" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeFirstIDclicked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeSecondIDpresented" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeSecondIDclicked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeOptionsPresented" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Option1ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Option2ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Option3ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OptionIDClicked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeOptionClicked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Word_Trial" Member="Word" ThisKey="WordID" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="Word_Trial1" Member="Word1" ThisKey="OptionIDClicked" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="Word_Trial2" Member="Word2" ThisKey="Option1ID" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="Word_Trial3" Member="Word3" ThisKey="Option2ID" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="Word_Trial4" Member="Word4" ThisKey="Option3ID" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="TrialBlock_Trial" Member="TrialBlock" ThisKey="TrialBlockID" OtherKey="ID" Type="TrialBlock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrialBlock" Member="TrialBlocks">
    <Type Name="TrialBlock">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrialTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrialBlock_Trial" Member="Trials" ThisKey="ID" OtherKey="TrialBlockID" Type="Trial" />
      <Association Name="TrialType_TrialBlock" Member="TrialType" ThisKey="TrialTypeID" OtherKey="ID" Type="TrialType" IsForeignKey="true" />
      <Association Name="User_TrialBlock" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="StudiesUser_TrialBlock" Member="StudiesUser" ThisKey="UserID,StudyID" OtherKey="StudyID,UserID" Type="StudiesUser" IsForeignKey="true" />
      <Association Name="Study_TrialBlock" Member="Study" ThisKey="StudyID" OtherKey="ID" Type="Study" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudiesUsers" Member="StudiesUsers">
    <Type Name="StudiesUser">
      <Column Name="StudyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WordListID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordSublistID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrialTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ControlGroup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="StudiesUser_TrialBlock" Member="TrialBlocks" ThisKey="StudyID,UserID" OtherKey="UserID,StudyID" Type="TrialBlock" />
      <Association Name="TrialType_StudiesUser" Member="TrialType" ThisKey="TrialTypeID" OtherKey="ID" Type="TrialType" IsForeignKey="true" />
      <Association Name="User_StudiesUser" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="WordList_StudiesUser" Member="WordList" ThisKey="WordListID" OtherKey="ID" Type="WordList" IsForeignKey="true" />
      <Association Name="WordSublist_StudiesUser" Member="WordSublist" ThisKey="WordSublistID" OtherKey="ID" Type="WordSublist" IsForeignKey="true" />
      <Association Name="Study_StudiesUser" Member="Study" ThisKey="StudyID" OtherKey="ID" Type="Study" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Study" Member="Studies">
    <Type Name="Study">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TargetWordsPerMinute" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlConsequenceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Study_TrialBlock" Member="TrialBlocks" ThisKey="ID" OtherKey="StudyID" Type="TrialBlock" />
      <Association Name="Study_StudiesUser" Member="StudiesUsers" ThisKey="ID" OtherKey="StudyID" Type="StudiesUser" />
      <Association Name="Consequence_Study" Member="Consequence" ThisKey="ControlConsequenceID" OtherKey="ID" Type="Consequence" IsForeignKey="true" />
    </Type>
  </Table>
</Database>